AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  my-golang-app
  Sample SAM Template for my-golang-app

Globals:
  Function:
    Timeout: 5

Parameters: 
  Stage: 
    Type: String    
    Default: dev
    AllowedValues:
      - dev
      - stage 
      - prod

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: hello-world/
      Handler: hello-world
      Runtime: go1.x
      Tracing: Active 
      Events:
        CatchAll:
          Type: Api 
          Properties:
            Path: /hello
            Method: GET
      Environment: 
        Variables:
          PARAM1: VALUE

  DontTouchThis:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: nana/
      Handler: nana
      Runtime: go1.x
      Tracing: Active 
      Events:
        CatchAll:
          Type: Api 
          Properties:
            Path: /hello-dos
            Method: GET
      Environment: 
        Variables:
          PARAM1: VALUE    

  AliasVersion:
    Type: AWS::Serverless::Function 
    DeletionPolicy: Retain
    Properties:
      FunctionName: !Sub 'AliasVersion-${Stage}'
      CodeUri: AliasVersion/
      Handler: !Sub 'AliasVersion-${Stage}'
      Runtime: go1.x
      Tracing: Active 
      Environment: 
        Variables:
          PARAM1: VALUE

Outputs:
  HelloWorldAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  DontTouchThis:
    Description: "Second Lambda Function ARN"
    Value: !GetAtt DontTouchThis.Arn    
  
    Description: "Second Lambda Function ARN"
    Value: !GetAtt AliasVersion.Arn
      #!Join ["-", [AliasVersion, !Ref Stage]]:
    #Value: !GetAtt AliasVersion.Arn        
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
